export const signUpTitle = "Sign up";
export const invalidEmail = "Invalid email";
export const errorLength = "8 characters minimum";
export const errorCPass = "Password should match";
export const isRequired = " is required";
export const passwordForm = "Password";
export const emailForm = "Email";
export const confirmPassForm = "Confirm password";
export const passwordContainsDigits = "Password can't contain only digits";